### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: mcjty/theoneprobe/network/PacketGetInfo

### ISSUE THREAD

**Issue by tier940** [ukmojb/The-One-Probe-Community-Edition#10]
This problem did not occur in 1.2.2, but has been occurring since 1.2.4. It seems that the update between 1.2.2 and 1.2.4 is to blame.

version
- 1.2.5

use modpack
- https://www.curseforge.com/minecraft/modpacks/gregtech-expert-2

error log
- https://mclo.gs/MgLE4OS

**Comment by ukmojb** [comment]
I changed some of the methods by making the module's display information client-side. Some modules (such as ae2, gregtech) use asm to enter the server and return information to the client to localize the displayed information, so they are not registered through the api provided by top, so they will report errors or crash. Unfortunately I moved this method to the client side, otherwise the original purpose of this community version (to localize the information display) would be violated (I18n method is only on the client side, so it will crash once it is run on the server side).

**Comment by ukmojb** [comment]
> 顺便说一句，如果无法改进，CE 将在 ModPack 中更改为已弃用，您将返回到无 CE。

In fact, all it takes is for gregtech to change the registration information to use api registration.))))

**Comment by ukmojb** [comment]
> Incidentally, if improvement is not possible, the CE will be changed to deprecated in the ModPack, and you will go back to no CE.

When I have time, I fork that mods to make it work with topce(All we know so far is ae2,gregtech)

**Comment by ukmojb** [comment]
> Incidentally, if improvement is not possible, the CE will be changed to deprecated in the ModPack, and you will go back to no CE.

If there are other modules that have the same problem, then feedback is welcome

**Comment by ukmojb** [comment]
1.2.6 fixed
